import_from_git(
  url: "git@github.com:starburst997/mac-code-sign.git",
  branch: "v1",
  path: "fastlane/Fastfile_iOS"
)

import_from_git(
  url: "git@github.com:starburst997/mac-code-sign.git",
  branch: "v1",
  path: "fastlane/Fastfile_macOS"
)