name: Build iOS (TestFlight)

on: 
  #push
  #pull_request
  workflow_dispatch:

jobs:
  releaseToAppStore:
    uses: starburst997/mac-code-sign/.github/workflows/ios.yml@v1
    secrets: inherit
    with:
      project_path: iOS
      project_target: Test
      xcodeproj_path: Test.xcodeproj
      plist_path: Test/Test.plist
      version: "2025.1"
      build_path: build
      artifact: true