name: Build Mac

on: 
  #push
  #pull_request
  workflow_dispatch:

jobs:
  build:
    uses: starburst997/apple-code-sign/.github/workflows/mac.yml@v1
    secrets: inherit
    with:
      project_path: macOS
      xcodeproj_path: Test.xcodeproj
      plist_path: Test/Info.plist
      project_target: Test
      version: "2025.1"
      artifact: true