name: Build Mac (TestFlight)

on: 
  #push
  #pull_request
  workflow_dispatch:

jobs:
  releaseToAppStore:
    uses: starburst997/mac-code-sign/.github/workflows/mac.yml@v1
    secrets: inherit
    with:
      project_path: macOS
      project_target: Test
      xcodeproj_path: Test.xcodeproj
      plist_path: Test/Info.plist
      version: "2025.1"
      build_path: build
      artifact: true